apiVersion: v1
imagePullSecrets:
- name: registry
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ci.nerdalize.com/author: "{{ .Values.ci.gitlab.user_name }} <{{ .Values.ci.gitlab.user_email }}>"
    ci.nerdalize.com/pipeline: "{{ .Values.ci.project.url }}/pipelines/{{ .Values.ci.pipeline.id }}"
  labels:
    app.kubernetes.io/name: {{ include "netbox.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "netbox.chart" . }}
  name: {{ include "netbox.fullname" . }}
